aws-region    = "us-east-1"
vpc-name      = "Jenkins-vpc"
igw-name      = "Jenkins-igw"
subnet-name   = "Jenkins-subnet"
rt-name       = "Jenkins-route-table"
sg-name       = "Jenkins-sg"
instance-name = "Jenkins-server"
key-name      = "your-key-name"    # ← غيّر لاسم مفتاحك على AWS
iam-role      = "Jenkins-iam-role"
instance-type = "t3.2xlarge"
volume-size   = 40
